#!/usr/bin/env bash

printf "\e[33;1m%s\e[0m\n" 'Running the Flutter analyzer'
ANALYZE_COMMAND="analyze"
if command -v fvm >/dev/null 2>&1; then
  fvm flutter $ANALYZE_COMMAND
else
  flutter $ANALYZE_COMMAND
fi
if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" 'Flutter analyzer error'
  exit 1
fi
printf "\e[33;1m%s\e[0m\n" 'Finished running the Flutter analyzer'
